# Generated by Django 2.2.1 on 2019-05-25 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('score', models.FloatField(blank=True, default=0, null=True)),
                ('time', models.CharField(max_length=64)),
                ('place', models.CharField(max_length=64)),
                ('school', models.CharField(max_length=32)),
                ('code', models.CharField(max_length=32)),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_id', to='rbac.UserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='SC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=32)),
                ('score', models.FloatField(blank=True, default=0, null=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_id', to='rbac.UserInfo')),
            ],
        ),
    ]
