# Generated by Django 2.1.2 on 2019-05-20 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=32)),
                ('role', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=32)),
                ('gender', models.CharField(max_length=5)),
                ('birthday', models.DateField()),
                ('grade', models.DateField()),
                ('school', models.CharField(max_length=32)),
                ('major', models.CharField(max_length=32)),
                ('cclass', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=32)),
                ('role', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=32)),
                ('diploma', models.CharField(max_length=32)),
                ('rate_times', models.IntegerField(default=1)),
                ('rate', models.FloatField(default=10.0)),
            ],
        ),
    ]
