# Generated by Django 2.1.2 on 2019-06-03 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={'verbose_name': '管理员资料管理', 'verbose_name_plural': '管理员资料管理'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': '学生资料管理', 'verbose_name_plural': '学生资料管理'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': '教师资料管理', 'verbose_name_plural': '教师资料管理'},
        ),
        migrations.AddField(
            model_name='admin',
            name='school',
            field=models.CharField(default='', max_length=32, verbose_name='院系'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='birthday',
            field=models.DateField(null=True, verbose_name='出生日期'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='gender',
            field=models.CharField(default='', max_length=5, verbose_name='性别'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='school',
            field=models.CharField(default='', max_length=32, verbose_name='院系'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='phone',
            field=models.CharField(max_length=32, verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='role',
            field=models.CharField(max_length=32, verbose_name='角色'),
        ),
        migrations.AlterField(
            model_name='student',
            name='birthday',
            field=models.DateField(null=True, verbose_name='出生日期'),
        ),
        migrations.AlterField(
            model_name='student',
            name='cclass',
            field=models.CharField(max_length=32, verbose_name='班级'),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(default='', max_length=5, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.CharField(max_length=16, verbose_name='年级'),
        ),
        migrations.AlterField(
            model_name='student',
            name='major',
            field=models.CharField(max_length=32, verbose_name='专业'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(max_length=32, verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='student',
            name='school',
            field=models.CharField(max_length=32, verbose_name='院系'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='diploma',
            field=models.CharField(max_length=32, verbose_name='学位'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone',
            field=models.CharField(max_length=32, verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='rate',
            field=models.FloatField(default=10.0, verbose_name='评分'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='rate_times',
            field=models.IntegerField(default=1, verbose_name='评分次数'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='role',
            field=models.CharField(max_length=32, verbose_name='角色'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='title',
            field=models.CharField(max_length=32, verbose_name='职称'),
        ),
    ]
